### ISSUE TITLE
Missing connection between some steps

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1288] opened 2023-02-20 13:11 UTC
### Describe the Bug

When adding some steps, the connection between them are missing. For instance on Camel Route, addign a Timer, then a Twitter-direct-message:

```
- from:
    uri: timer:demo
    steps:
    - to:
        uri: twitter-directmessage:example
```

error in console:
```
[React Flow]: Couldn't create edge for target handle id: "undefined", edge id: e-node_0-timer-0-3021662780>node_1-twitter-directmessage-1-4256420496. Help: https://reactflow.dev/error#008
devWarn | @ | index.js:149
-- | -- | --
  | (anonymous) | @ | index.js:3209
  | (anonymous) | @ | index.js:3187
  | EdgeRenderer | @ | index.js:3187
  | renderWithHooks | @ | react-dom.development.js:16305
  | updateFunctionComponent | @ | react-dom.development.js:19588
  | updateSimpleMemoComponent | @ | react-dom.development.js:19425
  | beginWork | @ | react-dom.development.js:21678
  | beginWork$1 | @ | react-dom.development.js:27426
  | performUnitOfWork | @ | react-dom.development.js:26560
  | workLoopSync | @ | react-dom.development.js:26466
  | renderRootSync | @ | react-dom.development.js:26434
  | performSyncWorkOnRoot | @ | react-dom.development.js:26085
  | flushSyncCallbacks | @ | react-dom.development.js:12042
  | flushSyncCallbacksOnlyInLegacyMode | @ | react-dom.development.js:12021
  | batchedUpdates$1 | @ | react-dom.development.js:26148
  | batchedUpdates | @ | react-dom.development.js:3991
  | dispatchEventForPluginEventSystem | @ | react-dom.development.js:9287
  | dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay | @ | react-dom.development.js:6465
  | dispatchEvent | @ | react-dom.development.js:6457
  | dispatchDiscreteEvent
```

### Steps to Reproduce the Bug or Issue

1. Go to settings -> Type Camel Route
2. Click on add a step and DnD Timer from left panel
3. Click on + and add twitter-direct-message

### Screenshots or Videos

![missingConnection](https://user-images.githubusercontent.com/1105127/220117979-340533b7-2d23-4a62-99e8-2f56b5087804.gif)

### Platform

- OS: Fedora
- Browser: VS Code
- Version: Kaoto UI 0.6.1, Kaoto backend 0.6.2

**Comment by apupier** [comment] 2023-02-20 14:03
reproduced with: Integration type and ActiveMQ in VS Code

not reproduced on Operate first http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/ so fixed on main branch or specific to VS Code?

**Comment by apupier** [comment] 2023-02-21 08:19
reproduced with main Kaoto UI in VS Code, so seems specific to VS Code

**Comment by lhein** [comment] 2023-03-01 09:37
cannot reproduce with original example on OperateFirst

**Comment by apupier** [comment] 2023-03-01 09:40
I can still reproduce:

![reproducerMissingConnection](https://user-images.githubusercontent.com/1105127/222101411-39c20dc6-780e-4d41-876b-f2803b4be829.gif)

**Comment by lhein** [comment] 2023-03-01 09:40
reproduced the problem when using the "save" button in code editor

**Comment by unsortedhashsets** [comment] 2023-03-01 14:27
Hi @lhein @apupier @igarashitm,

I have an assumption that the root problem is that these elements can be either `start` or `actions` or `end`. And after `Sync your code` step "downgrade" happens, `actions` become `start`, `end` become `actions`, but it happens only if in canvas is only one `start` step with type `source`, so repetition does not repeat the "downgrade". Below are some examples to confirm the assumption. Hope it helps you.

In your case all parts became `source` step:
![Screenshot from 2023-03-01 15-07-07](https://user-images.githubusercontent.com/46084942/222163827-c206db7e-6204-4de1-9424-a965a3daef23.png)
![Screenshot from 2023-03-01 15-07-01](https://user-images.githubusercontent.com/46084942/222163844-9aa43150-31fc-456b-bd35-2ed83341763b.png)

I faced a similar issue (here in example timer can be only `start` step and log can be `actions` or `end` step:

1) Through canvas added timer(start) -> log(end) :
![Screenshot from 2023-03-01 15-09-27](https://user-images.githubusercontent.com/46084942/222164310-215f2af2-fecd-4895-88e3-350e9666bad6.png)

2) Click on `Sync your code` => log step now is `actions` step
![Screenshot from 2023-03-01 15-09-54](https://user-images.githubusercontent.com/46084942/222164427-51ec771e-31cd-4d5a-a0aa-e4e5443746c7.png)

Also another example:
timer(start) -> activemq(actions) -> log(end)

possible positions for
- timer: start
- activemq: start, actions, end
- log: actions, end

After `Sync your code` all positions are "downgraded" on one step: timer(start),  activemq(start) -> log(actions)
![Screenshot from 2023-03-01 15-11-21](https://user-images.githubusercontent.com/46084942/222164878-83e1b807-e0e8-4357-91a8-a6dd8bce5c27.png)

In case activemq(start) -> activemq(actions) -> activemq(end):

1) Init state: activemq(start) -> activemq(actions) -> activemq(end)
2) After `Sync your code`: activemq(start), activemq(start) -> activemq(actions)
3) No changes after the second `Sync your code`, but any changed/newly added `end` will be "downgraded" to `actions`

**Comment by lhein** [comment] 2023-03-01 16:13
good catch!

**Comment by igarashitm** [comment] 2023-03-01 18:37
Good catch indeed @unsortedhashsets , this fixes it for `Camel Route` - https://github.com/KaotoIO/kaoto-backend/pull/498

I'll keep this open now and see if there's any other case we need to cover.

**Comment by unsortedhashsets** [comment] 2023-03-02 08:14
Hi, @igarashitm I have just checked the issue with the main backend, seems to be fixed :+1: 

Init state:
![Screenshot from 2023-03-02 09-12-30](https://user-images.githubusercontent.com/46084942/222369753-a42b1b5c-3214-4acc-beba-e2ec78f79f6f.png)

State after `Sync`:
![Screenshot from 2023-03-02 09-12-34](https://user-images.githubusercontent.com/46084942/222369814-c8a9a13b-888a-4ee1-8041-9f47ad912e26.png)

I will look for the issue with `end` state "downgrade" asap or create a separate issue!

**Comment by igarashitm** [comment] 2023-03-02 12:27
Wheter it's `Sink` or `Action`, IOW `MIDDLE` or `END` - it might affect the real DSL only on KameletBinding which has `sink` explicitly. Just a guess, would want a confirmation from Kaoto expert :-)

**Comment by Delawen** [comment] 2023-03-03 12:57
That's... intended. Because you can add more things after activemq.

**Comment by igarashitm** [comment] 2023-03-06 15:59
So https://github.com/KaotoIO/kaoto-backend/issues/497 was the one to be fixed for this issue. Closing

**Closed by igarashitm** 2023-03-06 15:59 UTC
Labels: bug, visualization
