### ISSUE TITLE
Delete Kamelet and KameletBinding type - can't create new route when there is empty list

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2085] opened 2023-07-03 07:32 UTC
### Describe the Bug

When users create Kamelet or KameletBinding route type and delete the route using the delete route button in the dropdown list, the "new route" button stays disabled and users can't create new route of this type.

### Steps to Reproduce the Bug or Issue

1. create kamelet or kameletbinding
2. delete the route using the delete button in the dropdown list
3. see the "new route" remains disabled

### Screenshots or Videos

![Peek 2023-07-03 09-29](https://github.com/KaotoIO/kaoto-ui/assets/4180208/c3e510d7-dc6c-4120-b12f-33d45a549fe0)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by igarashitm** [comment] 2023-07-03 12:00
It would be a same root cause with #2077

**Comment by lordrip** [comment] 2023-07-10 07:10
Fixed by #2111

**Closed by lordrip** 2023-07-10 07:10 UTC
Labels: bug
