### ISSUE TITLE
Missing link between steps for a specific example (after a log component?)

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1565] opened 2023-03-27 15:57 UTC
### Describe the Bug

example extracted from https://github.com/redhat-sa-brazil/demo-summitgov-cy20/blob/3abdc7e3e11b4305fce0f2d21631b6637c12c2d8/resources/application/demo-saude-digital/camel-k-integrations.yaml#L39

### Steps to Reproduce the Bug or Issue

1. open Source Code editor
2. paste
```yaml
- from:
    uri: knative:channel/mers-handler:null
    steps:
    - to:
        uri: log:info
    - to:
        uri: kafka:my-topic
        parameters:
          brokers: my-cluster-kafka-bootstrap.demo-saude-digital-streams.svc:9092
```
3. Click sync code
4. --> missing link between log and kafka

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1105127/227996423-1ed261c7-45b8-4775-9453-fbd8c00bbc1a.png)

### Platform

operateFirst

**Comment by apupier** [comment] 2023-03-28 07:38
similar behavior with this route:

```
- from:
    uri: knative://channel/returntxt:null
    steps:
    - unmarshal:
        json: {}
    - to:
        uri: log:null
    - to:
        uri: slack://sales-order
```

coming from https://github.com/redhat-sap/sap-odata4-camelk/blob/main/slack/SapSalesSlack.yaml

If I add build the route from Ui, it is working fine. i tis only when using the `Sync code` that the link is vanishing

**Comment by apupier** [comment] 2023-03-28 09:38
it seems that the log component is considered as an end step only although it can be a middle step. There is no + button after a log component in VS Code:

![image](https://user-images.githubusercontent.com/1105127/228194944-ee44c723-d197-4623-a518-ef740940bfe3.png)

but there is one with OperateFirst when addign an element:
![image](https://user-images.githubusercontent.com/1105127/228195031-784155a5-1397-427e-9a06-211bebe06910.png)

which is removed after clicking on `sync code`

![removedPlusButtonOnLogComponentWithSyncCode](https://user-images.githubusercontent.com/1105127/228195314-8a3d0242-9df9-49ab-aaea-07679c59220f.gif)

(the log EIP is workign fine)

**Comment by kahboom** [comment] 2023-03-29 15:11
Closing as duplicate of https://github.com/KaotoIO/kaoto-backend/issues/586 and https://github.com/KaotoIO/kaoto-ui/issues/1562

**Closed by kahboom** 2023-03-29 15:11 UTC
Labels: bug
