### ISSUE TITLE
Missing config when inserting action step between existing start and end steps

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#1369] opened 2023-03-03 09:57 UTC
### Describe the Bug

There are missing fields for middle "action" step, when it's inserted between two already specified start and end steps.

The config fields are visible when inserting prior to specifying the end step.

### Steps to Reproduce the Bug or Issue

1. specify start step
2. specify end step
3. specify middle action step - see there are no config fields present there

### Screenshots or Videos

![Peek 2023-03-03 10-52](https://user-images.githubusercontent.com/4180208/222690056-495ba35e-d364-4b84-8af6-e5e33865de76.gif)

### Platform

- OS: [Linux]
- Browser: [Chrome,Firefox]
- Version: [latest]

**Comment by mmelko** [comment] 2023-03-03 10:29
probably duplicate of #1370 working on fix.

**Closed** 2023-03-03 13:36 UTC
Labels: bug, step detail
