### ISSUE TITLE
Adding steps while having open the Code Editor makes it flash

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#1361] opened 2023-03-03 09:10 UTC
### Describe the Bug

When opening the Code Editor, if the user add steps, it flashes while being updated.

### Steps to Reproduce the Bug or Issue

1. Start with an empty canvas
2. Open the Code Editor
3. Add a step
4. Notice how the Code Editor flashes between updates

### Screenshots or Videos

[Screencast from 2023-03-03 10-10-28.webm](https://user-images.githubusercontent.com/16512618/222679658-d9a76182-59d6-461e-bd05-0fe5a3f5537c.webm)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [0.7.1-dev]

**Comment by lordrip** [comment] 2023-03-03 09:14
### First step
![Screenshot from 2023-03-03 10-13-30](https://user-images.githubusercontent.com/16512618/222680467-43f66c4a-06fc-417d-a3c3-5b54c7917ce9.png)

### Second step
![Screenshot from 2023-03-03 10-14-09](https://user-images.githubusercontent.com/16512618/222680479-176a5ea1-d4e7-4909-8e90-bc3212fe0208.png)

**Comment by tplevko** [comment] 2023-06-13 13:27
This should be fixed once https://github.com/KaotoIO/kaoto-ui/pull/1927 gets merged.

It was AFAIK caused by the alert in the code editor and the syncSource being for a split second different from the actual source code

**Comment by lordrip** [comment] 2023-06-13 14:07
Yes, you're right, I tried it locally and it works better :ok_hand:

**Closed** 2023-06-13 14:07 UTC
Labels: bug, code editor
